import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from './page.module.css'
import NavBar from "@/components/NavBar/NavBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <header className={styles.headerBackground}>
          <div className={styles.container}>
            <NavBar />

            <h1>Знайдіть помешкання для наступної подорожі</h1>

          </div>
        </header>

        <div className={styles.mainContent}>
          <div className={styles.container}>

            {children}
          </div>
        </div>

      </body>
    </html>
  );
}
